clone:
  skip_verify: true

build:
  image: node:5
  environment:
    - VAULT_URL=http://127.0.0.1:8200
  commands:
    - vault/seed.sh > /dev/null
    - npm install
    - npm test
  link:
    - vault

compose:
  vault:
    image: joshq00/vault:dev
