clone:
  skip_verify: true

cache:
  mount:
  - node_modules
  - jq

build:
  image: node:5
  environment:
    - VAULT_URL=http://localhost:8200
    - NO_PROXY=localhost,127.0.0.1
  commands:
    - vault/seed.sh > /dev/null
    - npm install
    - npm test
  link:
    - vault

compose:
  vault:
    image: joshq00/vault:dev
