clone:
  skip_verify: true


cache:
  mount:
  - node_modules
  - jq


build:
  deps:
    image: node:$$NODE_VERSION
    commands:
    - npm install

  test:
    image: node:$$NODE_VERSION
    environment:
    - VAULT_URL=http://localhost:8200
    - NO_PROXY=localhost,127.0.0.1
    commands:
    - vault/seed.sh > /dev/null
    - npm test -- --color
    - npm run lint
    link:
    - vault

  server:
    image: node:$$NODE_VERSION
    commands:
    - npm run build


matrix:
  NODE_VERSION:
  - 5
  - 4
  - 0


compose:
  vault:
    image: joshq00/vault:dev


deploy:
  cloudfoundry:
    api: api.run-np.homedepot.com
    org: jq-org
    space: development
    user: $$USER
    password: $$PASSWORD
    when:
      branch: 'master'
      matrix:
        NODE_VERSION: 5
